#!/bin/bash

set -e

if [ "$LAB_LOADED" != "true" ]; then
    echo "Lab environment is not set. Please execute 'source ./0_lab_setenv' in the root lab directory"
    exit 1
fi

echo "Invoking generators for HelloWorld example"
./2_generate_project HelloWorld rpc 1

echo "Invoking generators for HelloWorldStruct example"
./2_generate_project HelloWorldStruct rpc_struct 1

echo "Invoking generators for Status example"
./2_generate_project Status field 1

echo "Invoking generators for Temperature example"
./2_generate_project Temperature event 1

echo "Generating CMake for HelloWorld example"
./3_generate_cmake HelloWorld rpc 1 v0/commonapi/examples

echo "Generating CMake for HelloWorldStruct example"
./3_generate_cmake HelloWorldStruct rpc_struct 1 v0/commonapi/examples

echo "Generating CMake for Status example"
./3_generate_cmake Status field 1 v0/commonapi/examples

echo "Generating CMake for Temperature example"
./3_generate_cmake Temperature event 1 v1/my_package/iartn/some_ip_demo

echo "Building HelloWorld example"
./4_build_project rpc 1

echo "Building HelloWorldStruct example"
./4_build_project rpc_struct 1

echo "Building Status example"
./4_build_project field 1

echo "Building Temperature example"
./4_build_project event 1