#!/bin/bash

set -e

if [ "$LAB_LOADED" != "true" ]; then
    echo "Lab environment is not set. Please execute 'source ./0_lab_setenv' in the root lab directory"
    exit 1
fi

echo "Invoking generators for HelloWorld example"
./2_generate_project HelloWorld rpc/Instance_1

echo "Invoking generators for HelloWorldStruct example"
./2_generate_project HelloWorldStruct rpc_struct/Instance_1

echo "Invoking generators for Status example"
./2_generate_project Status field/Instance_1

echo "Invoking generators for Temperature example"
./2_generate_project Temperature event/Instance_1

echo "Generating CMake for HelloWorld example"
./3_generate_cmake HelloWorld rpc/Instance_1 v0/commonapi/examples

echo "Generating CMake for HelloWorldStruct example"
./3_generate_cmake HelloWorldStruct rpc_struct/Instance_1 v0/commonapi/examples

echo "Generating CMake for Status example"
./3_generate_cmake Status field/Instance_1 v0/commonapi/examples

echo "Generating CMake for Temperature example"
./3_generate_cmake Temperature event/Instance_1 v1/my_package/iartn/some_ip_demo

echo "Building HelloWorld example"
./4_build_project rpc/Instance_1

echo "Building HelloWorldStruct example"
./4_build_project rpc_struct/Instance_1

echo "Building Status example"
./4_build_project field/Instance_1

echo "Building Temperature example"
./4_build_project event/Instance_1
