#!/bin/bash

set -e

# Check if both arguments are provided
if [ "$#" -ne 4 ]; then
    echo "Usage: $0 <ServiceName> <ServiceFolder> <NumServiceInstances> <ServicePackage>"
    echo "Example: $0 HelloWorld rpc/Instance_1 commonapi.examples"
    exit 1
fi

SERVICE_NAME=$1
SERVICE_FOLDER=$2
NUM_INSTANCES=$3
SERVICE_PACKAGE=$4

PACKAGE_NAMESPACE="v1::${SERVICE_PACKAGE//./::}"
NAMESPACE_DIR="v1/${SERVICE_PACKAGE//.//}"

TARGET_DIR="${SERVICE_FOLDER}"

mkdir -p "$TARGET_DIR"

# multiple instances --> one "standard" folder structure for each instance

# i am inside IARTN_SOME_IP_Laboratory/projects/ServiceFolder

for i in $(seq 1 $NUM_INSTANCES); do

TARGET_DIR="${SERVICE_FOLDER}/Instance_${i}/fidl"
	
mkdir -p "$TARGET_DIR"

# Service interface file
OUTPUT_FILE="${SERVICE_NAME}.fidl"

echo "Writing service interface file: ${TARGET_DIR}/${OUTPUT_FILE}..."

cat <<EOF > "${TARGET_DIR}/${OUTPUT_FILE}"
package $SERVICE_PACKAGE

interface $SERVICE_NAME {
    version { major 1 minor 0 }

    struct StructName {
        type1 var1
        type2 var2
    }

    method methodName fireAndForget {
        in {
			type1 var1
			type2 var2 
        }
    }

    method methodName {
        in {
			type1 var1
			type2 var2
        }
        out {
			type1 var1
			type2 var2
        }
    }

    attribute type fieldName

    broadcast eventName {
        out {
			type1 var1
			type2 var2
        }
    }
}
EOF

echo "Service interface file successfully generated: ${TARGET_DIR}/${OUTPUT_FILE}"


# Service deployment file
OUTPUT_FILE="${SERVICE_NAME}.fdepl"

echo "Writing service deployment file: ${TARGET_DIR}/${OUTPUT_FILE}..."

cat <<EOF > "${TARGET_DIR}/${OUTPUT_FILE}"
import "platform:/plugin/org.genivi.commonapi.someip/deployment/CommonAPI-4-SOMEIP_deployment_spec.fdepl"
import "${SERVICE_NAME}.fidl"

define org.genivi.commonapi.someip.deployment for interface ${SERVICE_PACKAGE}.${SERVICE_NAME} {
    SomeIpServiceID = 

    method methodName {
        SomeIpMethodID = 
        SomeIpReliable = 
    }

    attribute fieldName{
        SomeIpGetterID =
        SomeIpSetterID =
        SomeIpNotifierID =
        SomeIpReliable =
        SomeIpNotifierEventGroups = { }
    }

    broadcast eventName {
        SomeIpEventID =
        SomeIpReliable =
        SomeIpEventgroups = { }
    }
}

define org.genivi.commonapi.someip.deployment for provider as Service {
    instance ${SERVICE_PACKAGE}.${SERVICE_NAME} {
        InstanceId = "${SERVICE_PACKAGE}.${SERVICE_NAME}.Instance_${i}"
        SomeIpInstanceID = 
        SomeIpUnicastAddress = ""
        SomeIpReliableUnicastPort =
        SomeIpUnreliableUnicastPort =
    }
}
EOF

echo "Service deployment file sucessfully generated: ${TARGET_DIR}/${OUTPUT_FILE}"

TARGET_DIR="${SERVICE_FOLDER}/Instance_${i}/src"
FILE_NAME="${SERVICE_NAME}Client.cpp"

# Create the directory if it doesn't exist
mkdir -p "$TARGET_DIR"

echo "Writing client source file: ${TARGET_DIR}/${FILE_NAME}..."

# Write the content to the file
cat <<EOF > "${TARGET_DIR}/${FILE_NAME}"
// ${FILE_NAME}
#include <iostream>
#include <string>
#include <thread>
#include <csignal>
#include <atomic>

#ifndef _WIN32
#include <unistd.h>
#endif

#include <CommonAPI/CommonAPI.hpp>
#include <${NAMESPACE_DIR}/${SERVICE_NAME}Proxy.hpp>

using namespace ${PACKAGE_NAMESPACE};

// Atomic flag to stop threads safely
std::atomic<bool> keepRunning(true);

// SIGINT handler
void signalHandler(int signum) {
    std::cout << "\nKilling ${SERVICE_NAME}Client ..." << std::endl;
    keepRunning = false;
}

int main() {
    CommonAPI::Runtime::setProperty("LogContext", "E01C");
    CommonAPI::Runtime::setProperty("LogApplication", "E01C");
    CommonAPI::Runtime::setProperty("LibraryBase", "${SERVICE_NAME}");

    std::shared_ptr < CommonAPI::Runtime > runtime = CommonAPI::Runtime::get();

    std::string domain = "local";
    std::string instance = "${SERVICE_PACKAGE}.${SERVICE_NAME}.Instance_${i}";
    std::string connection = "${SERVICE_NAME}_Instance_${i}_client";

    std::shared_ptr<${SERVICE_NAME}Proxy<>> myProxy = runtime->buildProxy<${SERVICE_NAME}Proxy>(domain,
            instance, connection);

    //SIGINT (Ctrl+C) handler declaration
    signal(SIGINT, signalHandler);

    std::cout << "Checking availability!" << std::endl;
    while (!myProxy->isAvailable() && keepRunning)
        std::this_thread::sleep_for(std::chrono::microseconds(10));
    std::cout << "Available..." << std::endl;

    while (keepRunning) {}

    return 0;
}
EOF

echo "Source file successfully generated: ${TARGET_DIR}/${FILE_NAME}"

FILE_NAME="${SERVICE_NAME}Service.cpp"

echo "Writing service source file: ${TARGET_DIR}/${FILE_NAME}..."

# Write the content to the file
cat <<EOF > "${TARGET_DIR}/${FILE_NAME}"
// ${FILE_NAME}
#include <iostream>
#include <thread>
#include <csignal>
#include <atomic>

#include <CommonAPI/CommonAPI.hpp>
#include "${SERVICE_NAME}StubImpl.hpp"

using namespace std;

using namespace ${PACKAGE_NAMESPACE};

// Atomic flag to stop threads safely
std::atomic<bool> keepRunning(true);

// SIGINT handler
void signalHandler(int signum) {
    std::cout << "\nKilling ${SERVICE_NAME}Service ..." << std::endl;
    keepRunning = false;
}

int main() {
    CommonAPI::Runtime::setProperty("LogContext", "E01S");
    CommonAPI::Runtime::setProperty("LogApplication", "E01S");
    CommonAPI::Runtime::setProperty("LibraryBase", "${SERVICE_NAME}");

    std::shared_ptr<CommonAPI::Runtime> runtime = CommonAPI::Runtime::get();

    std::string domain = "local";
    std::string instance = "${SERVICE_PACKAGE}.${SERVICE_NAME}.Instance_${i}";
    std::string connection = "${SERVICE_NAME}_Instance_${i}_server";
    
    std::shared_ptr<${SERVICE_NAME}StubImpl> myService = std::make_shared<${SERVICE_NAME}StubImpl>();
    bool successfullyRegistered = runtime->registerService(domain, instance, myService, connection);

    //SIGINT (Ctrl+C) handler declaration
    signal(SIGINT, signalHandler);

    while (!successfullyRegistered && keepRunning) {
        std::cout << "Register Service failed, trying again in 100 milliseconds..." << std::endl;
        std::this_thread::sleep_for(std::chrono::milliseconds(100));
        successfullyRegistered = runtime->registerService(domain, instance, myService, connection);
    }

    std::cout << "Successfully Registered Service!" << std::endl;

    while(keepRunning) {}
   
    return 0;
}
EOF

echo "Source file successfully generated: ${TARGET_DIR}/${FILE_NAME}"

FILE_NAME="${SERVICE_NAME}StubImpl"
FILE_EXT="${SERVICE_NAME}StubImpl.hpp"

FILE_NAME_UPPER=$(echo "$FILE_NAME" | tr '[:lower:]' '[:upper:]')

echo "Writing service interface source file: ${TARGET_DIR}/${FILE_EXT}..."

# Write the content to the file
cat <<EOF > "${TARGET_DIR}/${FILE_EXT}"
// ${FILE_EXT}
#ifndef ${FILE_NAME_UPPER}_H_
#define ${FILE_NAME_UPPER}_H_

#include <CommonAPI/CommonAPI.hpp>
#include <${NAMESPACE_DIR}/${SERVICE_NAME}StubDefault.hpp>

class ${FILE_NAME}: public ${PACKAGE_NAMESPACE}::${SERVICE_NAME}StubDefault {

public:
    ${FILE_NAME}();
    virtual ~${FILE_NAME}();
};
#endif /* ${FILE_NAME_UPPER}_H_ */
EOF

echo "Source file successfully generated: ${TARGET_DIR}/${FILE_EXT}"

FILE_NAME="${SERVICE_NAME}StubImpl.cpp"

echo "Writing service implementation source file: ${TARGET_DIR}/${FILE_NAME}..."

# Write the content to the file
cat <<EOF > "${TARGET_DIR}/${FILE_NAME}"
// ${FILE_NAME}
#include "${SERVICE_NAME}StubImpl.hpp"

${SERVICE_NAME}StubImpl::${SERVICE_NAME}StubImpl() {

}

${SERVICE_NAME}StubImpl::~${SERVICE_NAME}StubImpl() {

}

EOF

echo "Source file successfully generated: ${TARGET_DIR}/${FILE_NAME}"

TARGET_DIR="${SERVICE_FOLDER}/Instance_${i}"
FILE_NAME="vsomeip_client.json"

APP_NAME="${SERVICE_NAME}_Instance_${i}_client"

echo "Writing configuration file: ${TARGET_DIR}/${FILE_NAME}..."

# Write the content to the file
cat <<EOF > "${TARGET_DIR}/${FILE_NAME}"
{
    "unicast" : "", 
    "logging" : {
        "level" : "trace",
        "console" : "true"
    },
    "applications" : [
        {
            "name" : "$APP_NAME",
            "id" : ""
        }
    ],
    "routing" : "$APP_NAME",
    "service-discovery" : {
        "enable" : "true",
        "multicast" : "224.244.224.245",
        "port" : 30490,
        "protocol" : "udp",
        "initial_delay_min" : "10",
        "initial_delay_max" : "100",
        "repetitions_base_delay" : "200",
        "repetitions_max" : "3",
        "ttl" : "3",
        "cyclic_offer_delay" : "2000",
        "request_response_delay" : "1500"
    }
}
EOF

echo "Configuration file successfully generated: ${TARGET_DIR}/${FILE_NAME}"

FILE_NAME="vsomeip_server.json"

APP_NAME="${SERVICE_NAME}_Instance_${i}_server"

echo "Writing configuration file: ${TARGET_DIR}/${FILE_NAME}..."

# Write the content to the file
cat <<EOF > "${TARGET_DIR}/${FILE_NAME}"
{
    "unicast" : "", 
    "logging" : {
        "level" : "trace",
        "console" : "true"
    },
    "applications" : [
        {
            "name" : "$APP_NAME",
            "id" : ""
        }
    ],
	"services" : [
        {
            "service" : "",
            "instance" : "",
            "unreliable" :  ,
            "reliable" :  ,
        }
    ],
    "routing" : "$APP_NAME",
    "service-discovery" : {
        "enable" : "true",
        "multicast" : "224.244.224.245",
        "port" : 30490,
        "protocol" : "udp",
        "initial_delay_min" : "10",
        "initial_delay_max" : "100",
        "repetitions_base_delay" : "200",
        "repetitions_max" : "3",
        "ttl" : "3",
        "cyclic_offer_delay" : "2000",
        "request_response_delay" : "1500"
    }
}
EOF

echo "Configuration file successfully generated: ${TARGET_DIR}/${FILE_NAME}"

done