#!/bin/bash

set -e

if [ "$LAB_LOADED" != "true" ]; then
    echo "Lab environment is not set. Please execute 'source ./0_lab_setenv' in the root lab directory"
    exit 1
fi

if [ "$#" -ne 2 ]; then
    echo "Error: not enough arguments."
    echo "$0 <ServiceName> <ServiceFolder>"
    echo "Example: $0 HelloWorld rpc/Instance_1"
    exit 1
fi

SERVICE_NAME=$1
PRJ_DIR="$PROJ_ROOT/$2"

if [ ! -d "$PRJ_DIR" ]; then
    echo "Folder $PRJ_DIR does not exist. Error"
    exit 1
fi

echo "Running CommonAPI generators for: $SERVICE_NAME..."

cd "${PRJ_DIR}"

sudo commonapi-core fidl/${SERVICE_NAME}.fidl
sudo commonapi-dbus fidl/${SERVICE_NAME}.fidl
sudo commonapi-someip fidl/${SERVICE_NAME}.fdepl
