#!/bin/bash

set -e

if [ "$LAB_LOADED" != "true" ]; then
    echo "Lab environment is not set. Please execute 'source ./0_lab_setenv' in the root lab directory"
    exit 1
fi

if [ "$#" -ne 1 ]; then
    echo "Error: not enough arguments."
    echo "$0 <ServiceFolder>"
    echo "Example: $0 rpc/Instance_1"
    exit 1
fi

DEST_DIR=$1

cd $DEST_DIR 
cmake -Bbuild -DCMAKE_PREFIX_PATH=$INST_LIB_FOLDER -DPKG_CONFIG_USE_CMAKE_PREFIX_PATH=ON -DDBus1_DIR="$SRC_LIB_FOLDER/dbus-1.12.16/cmake" .
cmake --build build
