#!/bin/bash

set -e

if [ "$LAB_LOADED" != "true" ]; then
    echo "Lab environment is not set. Please execute 'source ./0_lab_setenv' in the root lab directory"
    exit 1
fi

if [ "$#" -ne 3 ]; then
    echo "Error: not enough arguments."
    echo "$0 <ServiceName> <ServiceFolder> <ServiceInstance>"
    echo "Example: $0 HelloWorld rpc 1"
    exit 1
fi

SERVICE_NAME=$1
FOLDER_NAME="$2/Instance_${3}"

ABS_PROJECT_PATH=$(realpath "$FOLDER_NAME")

INSTALL_LIB_PATH="$INST_LIB_FOLDER/lib"

CONFIG_PATH="$(realpath "./commonapi4someip.ini")"

BINARY_PATH="$ABS_PROJECT_PATH/build/${SERVICE_NAME}Client"
BUILD_LIB_PATH="$ABS_PROJECT_PATH/build"

if [ ! -f "$CONFIG_PATH" ]; then
    echo "CommonAPI configuration file does not find in $CONFIG_PATH"
    exit 1
fi

if [ ! -f "$BINARY_PATH" ]; then
    echo "Service executable does not find in $BINARY_PATH"
    exit 1
fi

echo "Running ${SERVICE_NAME}_Instance_${3}_Client..."

COMMONAPI_CONFIG="$CONFIG_PATH" \
VSOMEIP_CONFIGURATION="$ABS_PROJECT_PATH/vsomeip_client.json" \
VSOMEIP_APPLICATION_NAME="${SERVICE_NAME}_Instance_${3}_client" \
LD_LIBRARY_PATH="$INSTALL_LIB_PATH:$BUILD_LIB_PATH:$LD_LIBRARY_PATH" \
"$BINARY_PATH"